services:
  core:
    build: ./Core/RiffCore/RiffCore
    ports:
      - "3030:8080"
    networks:
      - main-network
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      rabbitmq:
        condition: service_healthy
      database:
        condition: service_healthy

  rabbitmqgotester:
    build: ./RabbitMQGoTester
    networks:
      - main-network
    depends_on:
      rabbitmq:
        condition: service_healthy

  accounts:
    build: ./AccountsService
    networks:
      - main-network
    depends_on:
      - core

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - main-network
    command: >
      mongod --quiet --logpath /dev/null
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand({ ping: 1 }).ok\" | grep 1"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 20s


  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - main-network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest    
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 20s
        



networks:
  main-network:
    driver: bridge